trigger:
  branches:
    include:
      - main

stages:
  - stage: Terraform_Plan
    displayName: "Terraform Plan (DEV)"
    jobs:
      - job: Plan
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - script: |
              sudo apt-get update
              sudo apt-get install -y wget unzip
              wget https://releases.hashicorp.com/terraform/1.13.5/terraform_1.13.5_linux_amd64.zip
              unzip terraform_1.13.5_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: "Install Terraform"

          - script: |
              cd infra/envs/dev
              terraform init
              terraform plan
            displayName: "Terraform Init & Plan"
